"""added artist website link

Revision ID: 46153366cfe8
Revises: f74c34045458
Create Date: 2020-04-21 18:44:42.406007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46153366cfe8'
down_revision = 'f74c34045458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
