"""testing default empty array

Revision ID: f74c34045458
Revises: 5d94352feff6
Create Date: 2020-04-21 18:23:45.338815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74c34045458'
down_revision = '5d94352feff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
